src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerAction.java, src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java, src/main/java/org/pentaho/di/job/entries/publish/JobEntryDatasourcePublish.java, src/main/resources/org/pentaho/di/job/entries/publish/messages/messages_en_US.properties, src/test/java/org/pentaho/di/job/entries/publish/JobEntryDatasourcePublishTest.java
What was done:
1) added implementation of rollback
2) added tests for rollback
=> BACKLOG-1765--  Special Characters - Model Name / Datasource

src/main/java/org/pentaho/di/job/entries/build/JobEntryBuildModel.java, src/main/java/org/pentaho/di/job/entries/publish/JobEntryDatasourcePublish.java, src/main/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationMeta.java, src/main/java/org/pentaho/di/trans/steps/annotation/SharedDimensionMeta.java
What was done:
1) updated version of docs
=> BACKLOG-6449 -- Update the help links in the SDR PDI steps/job entries

src/main/java/org/pentaho/di/ui/trans/steps/annotation/OptionsResolver.java, src/test/java/org/pentaho/di/ui/trans/steps/annotation/OptionsResolverTest.java
Annotate Stream step
What was done:
1) changed format
2) updated unit test
=> BACKLOG-7855 -- DEV: Update Format String options Create Measure in

src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java, src/main/java/org/pentaho/di/job/entries/build/DataServiceConnectionInformation.java, src/test/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublishTest.java, src/test/java/org/pentaho/di/job/entries/build/DataServiceConnectionInformationTest.java
Decided to take care of a single attribute for now because of a risk of regressions.
@mkambol
=> [BACKLOG-7483] Add the field "webapp name" for Pentaho Data Service database type (DSW)

pom.xml, src/test/java/org/pentaho/di/job/entries/build/MetadataInjectionModelTest.java
=> [BACKLOG-9909] Moved metainject step to plugin

src/main/java/org/pentaho/di/ui/job/entries/build/JobEntryBuildModelDialog.java
=> [SP-2909]- Backport of PDI-15329 - Build Model should read content from Metadata Injection when connect to Pentaho Repository (6.1 Suite)

pom.xml, src/main/java/org/pentaho/di/core/refinery/publish/util/ObjectUtils.java, src/test/java/org/pentaho/di/core/refinery/publish/util/ObjectUtilsTest.java
What was done:
removed xstream dependency
rewrote the code using it
=> [CLEANUP]-remove xstream

src/main/java/org/pentaho/di/core/refinery/publish/agilebi/BiServerConnection.java, src/main/java/org/pentaho/di/core/refinery/publish/model/DataSourcePublishModel.java
What was done:
Aded synchronized logic
=> BACKLOG-12261 - Remove xstream dependency from  data refinery plugin

pom.xml
@lgrill-pentaho @emartin-pentaho @e-cuellar @ViswesvarSekar
=> [ENGOPS-3148] groupId change for mavenized kettle plugins

pom.xml
DO NOT MERGE prior to merge of kettle mavenization!
=> [BACKLOG-12995] changes for upstream kettle mavenization

pom.xml, src/main/java/org/pentaho/di/core/refinery/model/ModelServerFetcher.java, src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java, src/main/java/org/pentaho/di/core/refinery/publish/util/BaseRestUtil.java, src/test/java/org/pentaho/di/core/refinery/publish/util/PublishRestUtilTest.java
Reverts pentaho/pentaho-data-refinery#88
=> Revert "[PPP-3735] - Use of vulnerable component httpclient-3.0.1.jar, common…"

src/main/java/org/pentaho/di/job/entries/build/JobEntryBuildModel.java, src/main/java/org/pentaho/di/job/entries/publish/JobEntryDatasourcePublish.java, src/main/java/org/pentaho/di/trans/steps/annotation/ModelAnnotationMeta.java, src/main/java/org/pentaho/di/trans/steps/annotation/SharedDimensionMeta.java
@pentaho/2-1b @pentaho/millenniumfalcon please review
=>  [BACKLOG-19262] Update In-Product Links to Documentation

pom.xml
@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186
=> [BACKLOG-13306] GAV change

pom.xml
=> [BACKLOG-27567] Centralize org.osgi dependencies management

pom.xml, src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java, src/test/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublishTest.java
@pentaho/millenniumfalcon please review
dependes on:
- https://github.com/pentaho/data-access/pull/1079
- https://github.com/pentaho/pentaho-platform/pull/4584
=> [BACKLOG-31895] CSFR - /data-access/api/connection/add

src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java, src/test/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublishTest.java
=> [BACKLOG-31893] Add CSRF security

pom.xml, src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerAction.java, src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java, src/test/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublishTest.java
- Update to use the simpler client filter CsrfTokenFilter (JAX-RS 1.1)
Please, review:
@graimundo
/cc @bennychow if you want to review, be my guest!
/cc @jcarneirohv
Depends on pentaho/security-web#4.
=> [BACKLOG-35000] CSRF refactor

pom.xml
=> [SP-6179][PPP-4654] Get commons-io version from parent pom

pom.xml, src/main/java/org/pentaho/di/core/refinery/model/ModelServerFetcher.java, src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerAction.java, src/main/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublish.java, src/main/java/org/pentaho/di/core/refinery/publish/util/BaseRestUtil.java, src/main/java/org/pentaho/di/core/refinery/publish/util/PublishRestUtil.java, src/test/java/org/pentaho/di/core/refinery/model/ModelServerFetcherTest.java, src/test/java/org/pentaho/di/core/refinery/publish/agilebi/ModelServerPublishTest.java, src/test/java/org/pentaho/di/core/refinery/publish/util/BaseRestUtilTest.java, src/test/java/org/pentaho/di/core/refinery/publish/util/PublishRestUtilTest.java
[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

pom.xml, src/main/java/org/pentaho/di/core/refinery/model/ModelServerFetcher.java, src/main/java/org/pentaho/di/core/refinery/publish/agilebi/BiServerConnection.java, src/main/java/org/pentaho/di/core/refinery/publish/util/JAXBUtils.java, src/test/java/org/pentaho/di/core/refinery/model/ModelServerFetcherTest.java
Resolve Unit Test cases of pentaho-data-refinery for Tomcat Upgrade 10.X
=> [BACKLOG-43492][Resolve Unit Test cases for Tomcat Upgrade 10.X]
